/*
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_ARCH_POWERPC_INCLUDE_OFFSETS_SHORT_ARCH_H_
#define ZEPHYR_ARCH_POWERPC_INCLUDE_OFFSETS_SHORT_ARCH_H_

#endif /* ZEPHYR_ARCH_POWERPC_INCLUDE_OFFSETS_SHORT_ARCH_H_ */
